# Generated by Django 5.0.6 on 2026-07-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0003_parsedresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.PositiveSmallIntegerField(help_text='ATS score out of 100.')),
                ('grade', models.CharField(help_text='Letter grade: A+, A, B, C, D.', max_length=5)),
                ('grade_label', models.CharField(default='', help_text='Human-readable grade label.', max_length=30)),
                ('summary', models.TextField(blank=True, default='', help_text='Human-readable assessment summary.')),
                ('breakdown', models.JSONField(default=dict, help_text='Per-category score breakdown.')),
                ('analysis', models.JSONField(default=dict, help_text='Full analysis: keywords found, warnings, missing sections.')),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_score', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'ATS Score',
                'verbose_name_plural': 'ATS Scores',
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
