# Generated by Django 5.0.6 on 2026-07-31 06:56

import apps.job_matching.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0003_parsedresume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title or role name.', max_length=255)),
                ('company', models.CharField(blank=True, default='', help_text='Company or organization name.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Raw or pasted job description text.')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.job_matching.models.jd_upload_path)),
                ('file_type', models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF'), ('docx', 'DOCX')], default='text', max_length=10)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='Structured requirements (required_skills, preferred_skills, experience_years, required_degree, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.PositiveSmallIntegerField(help_text='Total match score (0-100).')),
                ('grade', models.CharField(help_text='Match grade label (e.g. Excellent Match, Very Good, Good Match).', max_length=50)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('extra_skills', models.JSONField(blank=True, default=list)),
                ('experience_score', models.PositiveSmallIntegerField(default=0)),
                ('education_score', models.PositiveSmallIntegerField(default=0)),
                ('certification_score', models.PositiveSmallIntegerField(default=0)),
                ('keyword_score', models.PositiveSmallIntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='job_matching.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'Job Match',
                'verbose_name_plural': 'Job Matches',
                'ordering': ['-created_at'],
                'unique_together': {('job_description', 'resume')},
            },
        ),
    ]
