# Generated by Django 5.0.6 on 2026-07-31 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_matching', '0001_initial'),
        ('resumes', '0003_parsedresume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Software Engineer', help_text='Target job role (e.g., Python Developer, Backend Engineer).', max_length=200)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', help_text='Difficulty level: Easy | Medium | Hard', max_length=20)),
                ('interview_type', models.CharField(choices=[('HR', 'HR'), ('Technical', 'Technical'), ('Behavioral', 'Behavioral'), ('Coding', 'Coding'), ('Project Discussion', 'Project Discussion'), ('Mixed', 'Mixed Interview')], default='Mixed', help_text='Type of interview: HR | Technical | Behavioral | Coding | Project Discussion | Mixed', max_length=50)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', help_text='Session status: in_progress | completed | abandoned', max_length=20)),
                ('current_question', models.PositiveIntegerField(default=1, help_text='1-based index of the active question.')),
                ('total_questions', models.PositiveIntegerField(default=10, help_text='Total number of questions in this interview.')),
                ('completed_questions', models.PositiveIntegerField(default=0, help_text='Number of questions answered by the candidate.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job_description', models.ForeignKey(blank=True, help_text='Optional target job description.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_interviews', to='job_matching.jobdescription')),
                ('resume', models.ForeignKey(help_text='The resume used for this interview.', on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to='resumes.resume')),
                ('user', models.ForeignKey(help_text='The candidate taking this interview.', on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(help_text='Sequence index of the question within the session (1..N).')),
                ('category', models.CharField(default='Technical', help_text='Question category: HR | Technical | Resume | Project | Coding | Behavioral', max_length=50)),
                ('question', models.TextField(help_text='The interview question text presented to the candidate.')),
                ('user_answer', models.TextField(blank=True, default='', help_text="The candidate's response text.")),
                ('answered_at', models.DateTimeField(blank=True, help_text='Timestamp when the candidate submitted their answer.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='The parent interview session.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mock_interview.interviewsession')),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'ordering': ['session', 'question_number'],
                'unique_together': {('session', 'question_number')},
            },
        ),
    ]
