# Generated by Django 5.0.6 on 2026-07-31 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0003_parsedresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='Overall assessment summary.')),
                ('strengths', models.JSONField(blank=True, default=list, help_text='List of resume strengths.')),
                ('weaknesses', models.JSONField(blank=True, default=list, help_text='List of areas needing improvement.')),
                ('suggestions', models.JSONField(blank=True, default=list, help_text='List of actionable suggestions.')),
                ('priority_skills', models.JSONField(blank=True, default=list, help_text='Priority learning roadmap skills.')),
                ('improved_project_description', models.TextField(blank=True, default='', help_text='Sample rewritten project description.')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'AI Resume Suggestion',
                'verbose_name_plural': 'AI Resume Suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
