# Generated by Django 5.0.6 on 2026-07-31 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0003_parsedresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(blank=True, default='', help_text='Target job role (e.g. Backend Developer).', max_length=200)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', help_text='Interview difficulty level.', max_length=20)),
                ('question_count', models.PositiveSmallIntegerField(default=10, help_text='Number of questions generated.')),
                ('questions', models.JSONField(default=list, help_text='List of {id, category, question} dicts.')),
                ('provider', models.CharField(blank=True, default='', help_text='AI provider used (OpenRouter / OpenAI / Fallback).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(help_text='The resume this question set was generated for.', on_delete=django.db.models.deletion.CASCADE, related_name='interview_question_sets', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'Interview Question Set',
                'verbose_name_plural': 'Interview Question Sets',
                'ordering': ['-created_at'],
            },
        ),
    ]
